name: Econometrics and Data Science
name_cn: 计量经济学与数据科学
slug: econometrics-and-data-science
toc:
- - '#'
  - 计量经济学导论
- - '##'
  - 计量经济学
- - '#'
  - 1. 经济设计
- - '##'
  - 理解统计学
- - '###'
  - 机器学习建模
- - '###'
  - 深度学习建模
- - '###'
  - 结构方程模型
- - '##'
  - 宏观经济数据来源
- - '##'
  - 表 1-2 世界银行主题
- - '##'
  - 本书的背景
- - '##'
  - 实际应用意义
- - '#'
  - 2. 应用回归的单变量消费研究
- - '##'
  - 本章背景
- - '##'
  - 理论框架
- - '###'
  - 贷款利率
- - '###'
  - 最终消费支出（现价美元）
- - '##'
  - 正态性假设
- - '###'
  - 正态性检测
- - '##'
  - 描述性统计
- - '###'
  - 协方差分析
- - '##'
  - 相关性分析
- - '##'
  - 使用 Statsmodels 开发普通最小二乘回归模型
- - '###'
  - 使用 Scikit-Learn 开发普通最小二乘回归模型
- - '###'
  - 交叉验证
- - '####'
  - 预测
- - '##'
  - 估计截距和系数
- - '##'
  - 残差分析
- - '###'
  - 其他普通最小二乘回归模型性能指标
- - '##'
  - 普通最小二乘回归模型学习曲线
- - '###'
  - 结论
- - '#'
  - 3. 应用回归的多变量消费研究
- - '##'
  - 本章背景
- - '###'
  - 社会缴款（现价本币单位）
- - '###'
  - 贷款利率
- - '###'
  - GDP 增长（年度百分比）
- - '###'
  - 最终消费支出
- - '##'
  - 理论框架
- - '##'
  - 描述性统计
- - '###'
  - 协方差分析
- - '##'
  - 相关性分析
- - '##'
  - 相关性严重程度检测
- - '##'
  - 降维
- - '##'
  - 使用 Statsmodels 开发普通最小二乘法回归模型
- - '###'
  - 残差分析
- - '####'
  - 残差自相关
- - '##'
  - 使用 Scikit-Learn 开发普通最小二乘法回归模型
- - '###'
  - 交叉验证
- - '###'
  - 超参数优化
- - '###'
  - 残差分析
- - '##'
  - 普通最小二乘回归模型学习曲线
- - '###'
  - 结论
- - '#'
  - 4. 预测增长
- - '##'
  - 描述性统计
- - '###'
  - 平稳性检测
- - '###'
  - 随机白噪声检测
- - '##'
  - 自相关检测
- - '##'
  - 不同的单变量时间序列模型
- - '###'
  - 自回归积分滑动平均模型
- - '###'
  - 季节性自回归积分滑动平均模型
- - '##'
  - 加法模型
- - '##'
  - 加法模型开发
- - '##'
  - 加法模型预测
- - '###'
  - 季节性分解
- - '###'
  - 结论
- - '#'
  - 5. 应用逻辑回归对经济数据进行分类
- - '##'
  - 本章背景
- - '##'
  - 理论框架
- - '###'
  - 城市人口
- - '###'
  - 人均国民总收入，Atlas 法
- - '###'
  - 国内生产总值（GDP）增长
- - '###'
  - 出生时预期寿命，总计（年）
- - '##'
  - 描述性统计
- - '##'
  - 协方差分析
- - '##'
  - 相关性分析
- - '##'
  - 相关程度检测
- - '##'
  - 降维
- - '##'
  - 将连续变量转换为二值变量
- - '##'
  - 使用 Scikit-Learn 开发逻辑回归模型
- - '##'
  - 逻辑回归混淆矩阵
- - '##'
  - 逻辑回归混淆矩阵解读
- - '##'
  - 逻辑回归分类报告
- - '##'
  - 逻辑回归 ROC 曲线
- - '##'
  - 逻辑回归精确率-召回率曲线
- - '##'
  - 逻辑回归学习曲线
- - '###'
  - 结论
- - '#'
  - 6. 发现世界经济与增长中的隐藏模式
- - '##'
  - 应用隐马尔可夫模型
- - '##'
  - 描述性统计
- - '##'
  - 高斯混合模型开发
- - '##'
  - 以图形化方式表示隐状态
- - '###'
  - 阶数隐状态
- - '###'
  - 结论
- - '#'
  - 7. 按大洲层级对人均国民总收入进行聚类
- - '##'
  - 本章背景
- - '##'
  - 描述性统计
- - '###'
  - 降维
- - '###'
  - 聚类数量检测
- - '##'
  - K-Means 模型开发
- - '###'
  - 预测
- - '###'
  - 聚类中心检测
- - '###'
  - 聚类结果分析
- - '##'
  - K-Means 模型评估
- - '###'
  - 轮廓系数法
- - '###'
  - 结论
- - '#'
  - 8. 应用人工神经网络解决经济问题
- - '##'
  - 本章背景
- - '##'
  - 理论框架
- - '##'
  - 受限玻尔兹曼机分类器
- - '##'
  - 受限玻尔兹曼机分类器开发
- - '###'
  - 受限玻尔兹曼机混淆矩阵
- - '###'
  - 受限玻尔兹曼机分类报告
- - '###'
  - 受限玻尔兹曼机分类器 ROC 曲线
- - '###'
  - 受限玻尔兹曼机分类器精确率-召回率曲线
- - '###'
  - 受限玻尔兹曼机分类器学习曲线
- - '##'
  - 多层感知器（MLP）分类器
- - '###'
  - 多层感知器（MLP）分类器模型开发
- - '###'
  - 多层感知器分类报告
- - '###'
  - 多层感知器 ROC 曲线
- - '###'
  - 多层感知器分类器精确率-召回率曲线
- - '###'
  - 多层感知机分类器学习曲线
- - '##'
  - 基于 Keras 的人工神经网络原型设计
- - '##'
  - 人工神经网络结构构建
- - '###'
  - 网络封装
- - '###'
  - Keras 分类器混淆矩阵
- - '###'
  - Keras 分类报告
- - '###'
  - Keras 分类器 ROC 曲线
- - '###'
  - Keras 分类器 精确率-召回率曲线
- - '##'
  - 跨周期的训练损失和交叉验证损失
- - '##'
  - 跨周期的训练损失和交叉验证损失准确率
- - '###'
  - 结论
- - '#'
  - 9. 通货膨胀模拟
- - '##'
  - 理解模拟
- - '##'
  - 本章背景
- - '##'
  - 描述性统计
- - '##'
  - 蒙特卡洛模拟模型开发
- - '##'
  - 模拟结果
- - '##'
  - 模拟分布
- - '#'
  - 10. 应用结构方程模型的经济因果分析
- - '##'
  - 构建结构关系
- - '##'
  - 本章背景
- - '##'
  - 理论框架
- - '###'
  - 最终消费支出
- - '###'
  - 通货膨胀与消费者价格
- - '###'
  - 瑞典的预期寿命
- - '###'
  - 人均 GDP 增长
- - '##'
  - 协方差分析
- - '##'
  - 相关性分析
- - '##'
  - 相关严重程度分析
- - '##'
  - 结构方程模型估计
- - '##'
  - 结构方程模型开发
- - '##'
  - 结构方程模型信息
- - '##'
  - 结构方程模型检查
- - '###'
  - 报告指数
- - '###'
  - 可视化结构关系
- - '###'
  - 结论
