name: Data Modeling of Financial Derivatives
name_cn: 金融衍生品数据建模
slug: data-modeling-of-financial-derivatives
toc:
- - '#'
  - 内容排版
- - '#'
  - 金融衍生品的数据建模：一种概念性方法
- - '#'
  - 目录
- - '#'
  - 关于作者
- - '#'
  - 致谢
- - '#'
  - 前言
- - '#'
  - 第 1 章：引言
- - '##'
  - 本书目的
- - '##'
  - 目标读者
- - '##'
  - 本书结构
- - '##'
  - 数据建模模式的益处
- - '##'
  - 本书中使用的概念模型
- - '##'
  - 本书中的数据类型
- - '##'
  - 实践与专注
- - '##'
  - 提出正确的问题
- - '##'
  - 结论
- - '##'
  - 推荐阅读
- - '#'
  - 第 2 章：Barker 表示法
- - '##'
  - 不同类型的数据模型
- - '##'
  - 数据模型概述
- - '##'
  - 实体
- - '##'
  - 子类型和超类型
- - '###'
  - 在数据模型中表示子类型/超类型
- - '###'
  - 子类型/超类型规则
- - '##'
  - 属性
- - '##'
  - 关系
- - '##'
  - 关系规则
- - '##'
  - 子类型之间的关系
- - '##'
  - 建模递归关系
- - '###'
  - 递归一对多关系
- - '###'
  - 递归多对多关系
- - '###'
  - 递归一对一关系
- - '##'
  - 冗余关系
- - '##'
  - 互斥弧
- - '##'
  - Barker 的位置惯例
- - '##'
  - 结论
- - '##'
  - 推荐阅读
- - '#'
  - 第 3 章：合同基础
- - '##'
  - 什么是合同？
- - '##'
  - 维护合同参与历史
- - '##'
  - 区分合同与合同类型
- - '##'
  - 资产与资产类型
- - '##'
  - 所有权确认的重要性
- - '##'
  - 建模合同资产分配
- - '##'
  - 合同结构与合同类型结构
- - '##'
  - 合同变量及其分配
- - '##'
  - 业务策略
- - '##'
  - 抵押品
- - '##'
  - 合同交付（Contract Delivery）
- - '##'
  - 合同监管（Contract Regulations）
- - '##'
  - 结论
- - '##'
  - 推荐阅读
- - '#'
  - 第 4 章：远期合约建模
- - '##'
  - 定义远期合约
- - '##'
  - 远期合约规格
- - '##'
  - 远期合约终止
- - '##'
  - 合约类型子类型化
- - '##'
  - 远期合约数据建模基础
- - '##'
  - 将远期合约与资产类型关联
- - '##'
  - 远期合约与变量分配
- - '##'
  - 将远期合约与业务策略关联
- - '##'
  - 结算策略
- - '##'
  - 远期合同与交割
- - '##'
  - 远期合同与现金结算
- - '##'
  - 冲销远期合同
- - '##'
  - 远期合约的终止
- - '##'
  - 诉讼与违规
- - '##'
  - 结论
- - '#'
  - 第 5 章：期货合约建模
- - '##'
  - 雇佣关系建模
- - '##'
  - 对期货合约进行子类型化
- - '##'
  - 对期货合约参与关系进行建模
- - '##'
  - 将期货合约与纸质资产（资产类型）关联
- - '##'
  - 期货合约与变量分配（完整模型）
- - '##'
  - 期货合约与变量分配（简化模型）
- - '##'
  - 期货合约与变量观测
- - '##'
  - 保证金账户
- - '##'
  - 期货合约保证金账户模型
- - '##'
  - 期货合约交割
- - '##'
  - 期货合约展期
- - '##'
  - 期货与远期合约的差异总结
- - '##'
  - 结论
- - '#'
  - 第 6 章：建模期权
- - '##'
  - 期权头寸
- - '##'
  - 对冲指令
- - '##'
  - 对冲
- - '##'
  - 标的资产
- - '##'
  - 将期权合约与买方和卖方关联
- - '##'
  - 对期权合约与资产类型进行建模
- - '##'
  - 对期权资产类型进行建模
- - '##'
  - 将期权建模为实物资产
- - '##'
  - 建模期权资产分配
- - '##'
  - 数学模型的重要性
- - '##'
  - 根据历史数据计算波动率
- - '##'
  - 期权合约变量赋值
- - '##'
  - 期权合约结算类型
- - '##'
  - 自动行权
- - '##'
  - 了结期权合约
- - '##'
  - 裸期权
- - '##'
  - 期权交割主题域的建模
- - '##'
  - FLEX 期权
- - '##'
  - 标准期权合约与 FLEX 期权
- - '##'
  - 结论
- - '#'
  - 第 7 章：对高级期权策略进行建模
- - '##'
  - 一个涉及一只股票和一个期权的简单策略
- - '##'
  - 期权策略元数据建模
- - '##'
  - TRADING STRATEGY 元数据建模
- - '##'
  - 牛市价差
- - '##'
  - 熊市价差
- - '##'
  - 重新审视合约结构实体
- - '##'
  - 结论
- - '##'
  - 推荐阅读
- - '#'
  - 第 8 章：互换与远期利率协议
- - '##'
  - 互换合约与远期利率合约
- - '##'
  - 定义互换
- - '##'
  - 普通型利率互换
- - '##'
  - 固定对固定货币互换
- - '##'
  - 国际互换与衍生品协会
- - '##'
  - 对互换合约类型进行子类型化
- - '##'
  - 利率与利率类型
- - '##'
  - 固定利率与浮动利率参与方角色
- - '##'
  - 建模掉期合约参与
- - '##'
  - 建模掉期合约资产分配与支付计划
- - '##'
  - 掉期合约支付
- - '##'
  - 互换合约中的交割
- - '##'
  - 远期利率协议
- - '###'
  - FRA 合约类型
- - '###'
  - 建模 FRA 合约参与方
- - '###'
  - 建模 FRA 资产配置与偿付计划
- - '##'
  - 对 FRA 资产交割建模
- - '##'
  - 对 ISDA 文件与确认书建模
- - '##'
  - 结论
- - '#'
  - 第 9 章：临别感言与物理数据模型实现
- - '##'
  - 临别感言
- - '###'
  - 陷入困境时该怎么办
- - '###'
  - 在物理数据模型中实现子类型/超类型
- - '##'
  - 数据建模：超类型/子类型转换
- - '###'
  - 将超类型结构下推至关联子类型
- - '###'
  - 将子类型上卷至关联超类型
- - '###'
  - 在物理模型中保留超类型/子类型结构
- - '##'
  - 应该选择哪种方案？
- - '##'
  - 处理派生数据的方法
- - '##'
  - 采取行动
- - '##'
  - 结论
- - '##'
  - 推荐阅读
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
- - '#'
  - 其他您会感兴趣的 Apress 图书
