name: Personal Finance With Python
name_cn: Python 个人理财指南
slug: personal-finance-with-python
toc:
- - '#'
  - 引言
- - '##'
  - 本书涵盖内容
- - '###'
  - 盈利
- - '###'
  - 转换
- - '###'
  - 摊销
- - '###'
  - 预算
- - '###'
  - 投资
- - '###'
  - 消费
- - '##'
  - 本书读者对象
- - '##'
  - 阅读本书所需准备
- - '##'
  - 代码示例
- - '##'
  - 读者反馈
- - '###'
  - 关于作者与技术审校
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校
- - '#'
  - 第1章 环境设置
- - '##'
  - Anaconda
- - '##'
  - nteract
- - '###'
  - 注意
- - '###'
  - pip install
- - '##'
  - 数据
- - '#'
  - 第2章 利润
- - '##'
  - 挖矿
- - '##'
  - ROI
- - '##'
  - 内部收益率（IRR）
- - '###'
  - =IRR()
- - '##'
  - pandas
- - '###'
  - read_excel
- - '###'
  - 注意
- - '###'
  - xnpv
- - '###'
  - 说明
- - '###'
  - xirr
- - '##'
  - 再来一遍！
- - '##'
  - 结论
- - '#'
  - 第3章 转换
- - '##'
  - openexchangerates.org
- - '##'
  - 密钥
- - '##'
  - 文档
- - '##'
  - 封装
- - '###'
  - show_alternative
- - '####'
  - .apply
- - '##'
  - 结论
- - '#'
  - 第4章 摊销
- - '##'
  - 银行
- - '##'
  - 摊销
- - '##'
  - 还款额
- - '###'
  - 循环A
- - '###'
  - 循环B
- - '##'
  - 函数化
- - '##'
  - 评估
- - '##'
  - 结论
- - '#'
  - 第5章 预算
- - '##'
  - 日期
- - '###'
  - datetime
- - '##'
  - Timestamp
- - '####'
  - .normalize
- - '##'
  - 时间跨度
- - '##'
  - 现金流
- - '##'
  - 半月末频率（15号和月末）
- - '##'
  - 月初频率
- - '##'
  - 总计
- - '##'
  - 可视化
- - '###'
  - 更新
- - '###'
  - 注意
- - '##'
  - 假期一
- - '##'
  - 自然语言
- - '###'
  - get_dates
- - '##'
  - 乐趣
- - '##'
  - YAML
- - '##'
  - 函数化
- - '##'
  - 度假II
- - '##'
  - 加载YAML
- - '##'
  - 结论
- - '#'
  - 第6章 投资
- - '##'
  - 权衡取舍
- - '##'
  - 实例化
- - '###'
  - 价格
- - '###'
  - 临时伪造数据
- - '###'
  - 订单
- - '###'
  - 存款
- - '###'
  - 模拟
- - '###'
  - 行情
- - '####'
  - '`get_price`'
- - '####'
  - '`get_historical`'
- - '##'
  - 投资组合
- - '##'
  - 再平衡
- - '##'
  - 结论
- - '#'
  - 第7章 消费
- - '##'
  - Prophet
- - '##'
  - 购买记录
- - '###'
  - 注意
- - '##'
  - 预测
- - '##'
  - 可视化
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D, E, F, G, H
- - '##'
  - I
- - '##'
  - J, K, L
- - '##'
  - M
- - '##'
  - N, O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W, X
- - '##'
  - Y, Z
