name: Basic Python for Data Management, Finance, and Marketing
name_cn: 数据管理、金融与营销的 Python 入门指南
slug: basic-python-for-data-management-finance-and-marketing
toc:
- - '#'
  - 第 1 章：初识 Python
- - '#'
  - 安装 Python
- - '##'
  - 变量与数值类型
- - '#'
  - 字符串
- - '#'
  - 你的第一个程序
- - '#'
  - 使用 If、Elif 和 Else 进行逻辑判断
- - '##'
  - 方法
- - '##'
  - 列表与元组
- - '#'
  - 升序排序列表
- - '#'
  - 索引与切片
- - '#'
  - 客户地址处理与 Python 入门
- - '##'
  - 总结
- - '#'
  - 第 2 章：编写你自己的 Python 脚本
- - '##'
  - 确定循环
- - '##'
  - Range 函数
- - '#'
  - 嵌套 for 循环
- - '#'
  - 定义你自己的函数
- - '#'
  - 构建程序结构
- - '##'
  - 不定循环
- - '#'
  - 字典
- - '##'
  - 将信息写入文本文件
- - '##'
  - 从文本文件中读取信息
- - '#'
  - 第 3 章：使用 Pandas 进行数据分析
- - '###'
  - Series
- - '##'
  - DataFrame
- - '###'
  - 构建 DataFrame
- - '###'
  - 切片 DataFrame
- - '###'
  - 过滤 DataFrame
- - '#'
  - Pandas 中的逻辑运算
- - '###'
  - 从 CSV 文件读取数据
- - '##'
  - 合并数据集
- - '###'
  - 拼接数据集
- - '###'
  - 合并 DataFrame
- - '###'
  - Groupby
- - '##'
  - 总结
- - '#'
  - 第 4 章：使用 Python 收集数据
- - '###'
  - 网络爬虫
- - '##'
  - 列表推导式
- - '#'
  - 使用 Selenium 进行网页抓取
- - '##'
  - Selenium 简介
- - '#'
  - 使用 API
- - '##'
  - 获取 API 密钥
- - '##'
  - 理解 API 文档
- - '##'
  - 使用 Python 获取股票数据
- - '##'
  - 探索 API 响应
- - '##'
  - Pandas-Datareader
- - '##'
  - 直方图
- - '##'
  - 散点图
- - '###'
  - 饼图
- - '#'
  - 第 6 章：使用 Python 完成基本财务任务
- - '#'
  - NumPy Financial
- - '##'
  - 未来价值 `fv()`
- - '##'
  - 现值 `pv()`
- - '##'
  - 净现值 `npv()`
- - '##'
  - 风险价值 (VAR)
- - '##'
  - 蒙特卡洛模拟
- - '##'
  - 有效前沿
- - '##'
  - 基本面分析
- - '#'
  - 在 `subplot`方法中，数字`211`和`212`表示网格布局：第一个数字`2`代表行数，第二个数字`1`代表列数；每个子图仅占一列。最后一个数字则表示该子图在整个图形中的位置。
- - '##'
  - 财务比率
- - '#'
  - 第 7 章：使用 Google Analytics 和 Twitter
- - '##'
  - 开始使用 Google API 客户端
- - '###'
  - '图 7-3  '
- - '###'
  - 结合 Python 使用 Google Analytics
- - '####'
  - '图 7-4  '
- - '####'
  - '图 7-5  '
- - '#'
  - DataFrame `location` 与 Google Analytics 数据
- - '#'
  - Twitter 机器人
- - '##'
  - 安装 Tweepy
- - '##'
  - 与 Twitter 进行身份验证
- - '##'
  - 发送带媒体的推文
- - '#'
  - 基于数据库存储的推特营销活动
- - '#'
  - 使用 Python 进行电子邮件营销
- - '#'
  - 索引
- - '##'
  - A, B
- - '###'
  - Anaconda 包
- - '###'
  - 应用编程接口 (API)
- - '##'
  - C
- - '###'
  - 逗号分隔值 (CSV)
- - '###'
  - 临界线算法 (CLA)
- - '##'
  - D
- - '###'
  - DataFrame
- - '###'
  - 数据结构
- - '###'
  - 函数
- - '###'
  - G
- - '###'
  - 程序结构
- - '###'
  - 读取数据
- - '###'
  - 定循环/不定循环
- - '###'
  - 字典
- - '###'
  - 数字营销任务
- - '##'
  - E
- - '###'
  - 有效前沿技术
- - '###'
  - 电子邮件营销
- - '##'
  - F
- - '###'
  - 过滤过程
- - '###'
  - 金融任务
- - '#'
  - 有效边界
- - '#'
  - 基本面分析
- - '#'
  - 未来值 `fv()`
- - '#'
  - 存货周转率
- - '#'
  - 蒙特卡洛模拟
- - '#'
  - 净现值
- - '#'
  - Numpy
- - '#'
  - 现值
- - '#'
  - 比率
- - '#'
  - 风险价值
- - '#'
  - 循环/for 循环
- - '#'
  - '`append()` 方法'
- - '#'
  - 定义
- - '#'
  - 设计模式
- - '#'
  - '`format()` 函数'
- - '#'
  - if 语句
- - '#'
  - 迭代
- - '#'
  - 列表变量
- - '#'
  - 翻译
- - '#'
  - 基本面分析
- - '#'
  - 资产负债表
- - '#'
  - 条形图
- - '#'
  - 能力
- - '#'
  - 现金流量表
- - '#'
  - 公司
- - '#'
  - 定义
- - '#'
  - '`enterprise()` 函数'
- - '#'
  - 交易所交易基金
- - '#'
  - '`pip` 命令'
- - '#'
  - 绘制数据
- - '#'
  - '`profile()` 函数'
- - '#'
  - 收入数据
- - '#'
  - ROIC 和 ROE 比率
- - '#'
  - '`subplot()` 函数'
- - '#'
  - 估值
- - '#'
  - 可视化
- - '#'
  - 未来值（`fv()` 函数）
- - '#'
  - G
- - '#'
  - 收集数据
- - '#'
  - 应用程序编程接口
- - '#'
  - 信息
- - '#'
  - 列表推导式
- - '#'
  - Pandas-Datareader
- - '#'
  - Selenium
- - '#'
  - 网络爬取
- - '#'
  - 参见 网络爬取过程
- - '#'
  - Google Analytics
- - '#'
  - 账户用户管理
- - '#'
  - '`build()` 函数'
- - '#'
  - 构建选项
- - '#'
  - DataFrame
- - '#'
  - 字典表示法
- - '#'
  - 电子邮件/导航
- - '#'
  - 获取选项
- - '#'
  - for 循环
- - '#'
  - 整数和浮点数
- - '#'
  - JSON 文件
- - '#'
  - 库
- - '#'
  - 指标值
- - '#'
  - 页面浏览量与会话时长
- - '#'
  - '`pip` 命令'
- - '#'
  - '`plot()`/`pie()` 方法'
- - '#'
  - 请求方法
- - '#'
  - 响应方法
- - '#'
  - 服务账户页面
- - '#'
  - 排序
- - '#'
  - 源代码
- - '#'
  - 解包过程
- - '#'
  - 用户和会话指标
- - '#'
  - 值
- - '#'
  - 可视化
- - '#'
  - Groupby
- - '#'
  - H, I
- - '#'
  - 直方图
- - '#'
  - 超文本标记语言 (HTML)
- - '#'
  - J
- - '#'
  - JavaScript 对象表示法 (JSON)
- - '#'
  - K
- - '#'
  - '`keys()` 方法'
- - '#'
  - L
- - '#'
  - 折线图
- - '#'
  - '`grid()` 函数'
- - '#'
  - HEX/RGB 格式
- - '#'
  - '`legend()` 函数'
- - '#'
  - '`plot()` 函数'
- - '#'
  - 绘图语句
- - '#'
  - '`plt.grid()` 函数'
- - '#'
  - '`plt.legend()` 函数'
- - '#'
  - '`plt.plot()` 函数'
- - '#'
  - '`plt.style.use()` 方法'
- - '#'
  - '`plt.title()` 函数'
- - '#'
  - pyplot 模块
- - '#'
  - 标题/图例
- - '#'
  - 列表推导式
- - '#'
  - '`append()` 方法'
- - '#'
  - '`final_list`'
- - '#'
  - 收集数据
- - '#'
  - '`list_article`'
- - '#'
  - '`mega_list`'
- - '#'
  - '`open()` 函数'
- - '#'
  - 解析和清理信息
- - '#'
  - 字符串模板
- - '#'
  - 语法
- - '#'
  - 文本格式化
- - '#'
  - 网络爬取操作
- - '#'
  - '`zip()` 函数'
- - '#'
  - M
- - '#'
  - Matplotlib
- - '#'
  - 库
- - '#'
  - 折线图
- - '#'
  - 饼图
- - '#'
  - 散点图
- - '#'
  - 蒙特卡洛模拟
- - '#'
  - 定义
- - '#'
  - NumPy 数组
- - '#'
  - 绘图选项
- - '#'
  - 投资组合列表
- - '#'
  - '`random()` 函数'
- - '#'
  - '`show()` 方法'
- - '#'
  - 波动性
- - '#'
  - N
- - '#'
  - 净现值 (NPV)
- - '#'
  - 假设
- - '#'
  - 计算/绘制项目
- - '#'
  - 公司规划
- - '#'
  - 交叉利率
- - '#'
  - 定义
- - '#'
  - '`discount_rates`'
- - '#'
  - 几何对象
- - '#'
  - '`hline()`/`vline()` 函数'
- - '#'
  - '`intersection()` 方法'
- - '#'
  - LineString 操作
- - '#'
  - '`plot()` 函数'
- - '#'
  - 项目创建
- - '#'
  - 情景分析
- - '#'
  - '`xlim()` 方法'
- - '#'
  - '`ylim()` 方法'
- - '#'
  - '`zip()` 函数'
- - '#'
  - Numpy-Financial 包
- - '#'
  - O
- - '#'
  - 面向对象编程 (OOP)
- - '#'
  - P, Q
- - '#'
  - Pandas
- - '#'
  - CSV
- - '#'
  - 参见 逗号分隔值 (CSV)
- - '#'
  - DataFrame
- - '#'
  - Datareader
- - '#'
  - '`DataReader()` 函数'
- - '#'
  - 定义
- - '#'
  - 国内生产总值
- - '#'
  - IEX
- - '#'
  - 非农就业人数
- - '#'
  - '`pip` 命令'
- - '#'
  - '`plot.line()` 方法'
- - '#'
  - 接收数据
- - '#'
  - 数据集
- - '#'
  - 组合
- - '#'
  - 连接
- - '#'
  - '`drop` 关键字'
- - '#'
  - '`groupby()` 方法'
- - '#'
  - '`zip()` 函数'
- - '#'
  - 定义
- - '#'
  - 逻辑运算
- - '#'
  - 匿名函数
- - '#'
  - '`apply()` 方法'
- - '#'
  - 双函数
- - '#'
  - '`if` 和 `else` 条件'
- - '#'
  - lambda 语法
- - '#'
  - 逻辑运算
- - '#'
  - '`np.where` 函数'
- - '#'
  - NumPy 函数
- - '#'
  - '`where()` 函数'
- - '#'
  - 合并函数
- - '#'
  - 面板数据
- - '#'
  - 绘图工具
- - '#'
  - Series
- - '#'
  - 参见 Series
- - '#'
  - 复杂数据结构
- - '#'
  - 饼图
- - '#'
  - '`post()` 方法'
- - '#'
  - Python
- - '#'
  - Anaconda
- - '#'
  - 参见 Anaconda
- - '#'
  - 概念
- - '#'
  - 错误信息
- - '#'
  - 创建第一个程序
- - '#'
  - '`float()` 函数'
- - '#'
  - if, Elif/Else 语句
- - '#'
  - 布尔数据类型
- - '#'
  - 比较运算符
- - '#'
  - 文档
- - '#'
  - '`Elif` 关键字'
- - '#'
  - '`Else` 语句'
- - '#'
  - '`if` 语句'
- - '#'
  - 逻辑运算符
- - '#'
  - 构建决策结构
- - '#'
  - 索引/切片
- - '#'
  - 元素/字符
- - '#'
  - 获取元素
- - '#'
  - '`insert()` 方法'
- - '#'
  - 列表存储
- - '#'
  - 负索引
- - '#'
  - 负步长
- - '#'
  - 有序集合
- - '#'
  - 跳过选项
- - '#'
  - 字符串/元素
- - '#'
  - 安装过程
- - '#'
  - '`int()` 函数'
- - '#'
  - 学习过程
- - '#'
  - 列表/元组
- - '#'
  - '`append()` 方法'
- - '#'
  - 升序
- - '#'
  - 条件
- - '#'
  - 容器
- - '#'
  - 数据结构
- - '#'
  - '`help()` 函数'
- - '#'
  - 列表方法
- - '#'
  - 数字
- - '#'
  - 运算符
- - '#'
  - '`remove()` 方法'
- - '#'
  - '`sort()` 函数'
- - '#'
  - '`tuple()` 函数'
- - '#'
  - '`type()` 函数'
- - '#'
  - 元音/辅音
- - '#'
  - 方法
- - '#'
  - 概念
- - '#'
  - '`dir()` 函数'
- - '#'
  - '`len()` 函数'
- - '#'
  - 小写字符串
- - '#'
  - 字符串方法
- - '#'
  - '`upper()` 方法'
- - '#'
  - '`ord()` 函数'
- - '#'
  - '`print()` 语句'
- - '#'
  - 常规任务
- - '#'
  - '`str()` 函数'
- - '#'
  - 字符串
- - '#'
  - 税费与小费计算器
- - '#'
  - 变量/数值类型
- - '#'
  - 面积计算
- - '#'
  - 算术运算符
- - '#'
  - 内置函数
- - '#'
  - 大小写敏感
- - '#'
  - 数据类型
- - '#'
  - 表达式
- - '#'
  - 浮点数
- - '#'
  - 整数
- - '#'
  - 内存
- - '#'
  - 命名约定
- - '#'
  - 塑料瓶/玻璃
- - '#'
  - 保留字/关键字
- - '#'
  - 源代码
- - '#'
  - 存储信息
- - '#'
  - '`type()` 函数'
- - '#'
  - R
- - '#'
  - Range 函数
- - '#'
  - 降序
- - '#'
  - 索引值
- - '#'
  - '`len()` 函数'
- - '#'
  - 参数
- - '#'
  - '`range()` 函数'
- - '#'
  - '`requests.get()` 方法'
- - '#'
  - S
- - '#'
  - 散点图
- - '#'
  - '`annotate()` 函数'
- - '#'
  - 标注值
- - '#'
  - 颜色条刻度
- - '#'
  - '`enumerate()` 函数'
- - '#'
  - 插入语句
- - '#'
  - 交互式图形
- - '#'
  - 魔术函数
- - '#'
  - 内联格式
- - '#'
  - 笔记本模式
- - '#'
  - '`read_excel()` 函数'
- - '#'
  - Selenium
- - '#'
  - Amazon 登录页面
- - '#'
  - 自动化解决方案
- - '#'
  - '`BeautifulSoup()` 函数'
- - '#'
  - 浏览器窗口
- - '#'
  - 类别名称
- - '#'
  - '`Chrome()` 函数'
- - '#'
  - ChromeDriver
- - '#'
  - '`dir()` 函数'
- - '#'
  - div 容器
- - '#'
  - Excel 文件
- - '#'
  - 异常处理
- - '#'
  - 获取选项
- - '#'
  - '`find_element_by_id()` 方法'
- - '#'
  - '`get()` 方法'
- - '#'
  - 输入提示
- - '#'
  - 检查选项
- - '#'
  - Keys 模块
- - '#'
  - '`page.get()` 方法'
- - '#'
  - 产品页面
- - '#'
  - '`productTitle`'
- - '#'
  - try 和 except 块
- - '#'
  - 源代码
- - '#'
  - '`text` 方法'
- - '#'
  - 网页
- - '#'
  - 网络爬取
- - '#'
  - 命令提示符窗口
- - '#'
  - 文档
- - '#'
  - '`get-pip.py` 文件'
- - '#'
  - 安装
- - '#'
  - sudo 命令
- - '#'
  - 终端窗口
- - '#'
  - 网页开发
- - '#'
  - '`write()` 方法'
- - '#'
  - Series
- - '#'
  - 优势
- - '#'
  - 属性
- - '#'
  - 数据类型标识符
- - '#'
  - 定义
- - '#'
  - 字典
- - '#'
  - 差异
- - '#'
  - 除法运算
- - '#'
  - 同质
- - '#'
  - 一维结构
- - '#'
  - '`pd` 变量'
- - '#'
  - 关系型数据库
- - '#'
  - '`round()` 函数'
- - '#'
  - 字符串键
- - '#'
  - 向量化
- - '#'
  - T
- - '#'
  - Twitter 机器人
- - '#'
  - 创建账户
- - '#'
  - API 注册过程
- - '#'
  - '`image_path` 变量'
- - '#'
  - 媒体文件
- - '#'
  - '`OAuthHandler` 方法'
- - '#'
  - 会话列
- - '#'
  - 终端窗口
- - '#'
  - 令牌/秘密访问
- - '#'
  - Tweepy 文档
- - '#'
  - Tweepy 库
- - '#'
  - U
- - '#'
  - 统一资源定位符 (URL)
- - '#'
  - V
- - '#'
  - 风险价值 (VAR)
- - '#'
  - 协方差矩阵
- - '#'
  - '`cov()` 函数'
- - '#'
  - '`pct_change()` 方法'
- - '#'
  - DataFrame
- - '#'
  - 定义
- - '#'
  - '`describe()` 方法'
- - '#'
  - '`dot()` 方法'
- - '#'
  - '`dropna()` 方法'
- - '#'
  - '`head()` 方法'
- - '#'
  - Jupyter Notebook
- - '#'
  - 标准化历史价格
- - '#'
  - NumPy 数组
- - '#'
  - 绘制历史股票
- - '#'
  - '`ppf()` 方法'
- - '#'
  - 预测值
- - '#'
  - 检索历史价格
- - '#'
  - 风险计算
- - '#'
  - '`shift()` 方法'
- - '#'
  - '`sqrt()` 方法'
- - '#'
  - 字符串格式
- - '#'
  - 可视化
- - '#'
  - 定义
- - '#'
  - 直方图
- - '#'
  - 折线图
- - '#'
  - Matplotlib 库
- - '#'
  - 饼图
- - '#'
  - 散点图
- - '#'
  - W, X, Y, Z
- - '#'
  - 网络爬取过程
- - '#'
  - '`BeautifulSoup()` 函数'
- - '#'
  - Chrome 浏览器
- - '#'
  - 定义
- - '#'
  - '`find()`/`find_all()` 方法'
- - '#'
  - '`get()` 方法'
- - '#'
  - '`get_text()` 方法'
- - '#'
  - hrefs
- - '#'
  - HTML 标记
- - '#'
  - 信息
- - '#'
  - 检查选项
- - '#'
  - investing.com
- - '#'
  - 定位/检查行
- - '#'
  - 检查选项
- - '#'
  - requests 方法
- - '#'
  - Selenium
- - '#'
  - 文本元素
- - '#'
  - 变量标题
- - '#'
  - URL 站点
- - '#'
  - 网页链接
