name: Plan Your Financial Future
name_cn: 财务未来规划指南
slug: plan-your-financial-future
toc:
- - '#'
  - 规划你的财务未来
- - '#'
  - 第一版前言
- - '#'
  - 前言
- - '#'
  - 致谢
- - '#'
  - 第一部分
- - '##'
  - 1. 理解挑战：启动的必要性
- - '###'
  - 财富与 PADD 方法
- - '##'
  - 财务规划流程的步骤
- - '##'
  - 确定你当前的财务状况
- - '###'
  - 创建个人资产负债表
- - '##'
  - 创建现金流量表
- - '##'
  - 预算编制
- - '##'
  - 现金流与债务管理
- - '##'
  - 监控你的进度与生命周期规划
- - '##'
  - 你需要理财规划师吗？
- - '##'
  - 关于自助理财的一点说明
- - '##'
  - 财务规划师的类型
- - '##'
  - 注册金融理财师及其他理财规划资质
- - '##'
  - 向理财规划师提问的问题
- - '#'
  - 3. 个人财务规划与财富管理流程的要素
- - '##'
  - 个人财务规划与财富管理
- - '##'
  - 投资政策声明的必要性
- - '###'
  - 投资者目标的陈述
- - '###'
  - 投资约束或限制条件的陈述
- - '###'
  - 实现投资者目标与投资资源分配
- - '###'
  - 监控投资计划的表现
- - '##'
  - 多元化投资组合的基本原理
- - '##'
  - 再平衡的基本原理
- - '##'
  - 投资策略
- - '###'
  - 平均成本法与股票平均法
- - '###'
  - 向下摊平法
- - '###'
  - 股息再投资计划
- - '###'
  - 阶梯投资法
- - '###'
  - 买入并持有
- - '###'
  - 市场择时
- - '###'
  - 价值型投资与成长型投资
- - '##'
  - 房地产投资
- - '#'
  - 第二部分
- - '#'
  - 4. 为你自己和你的家人投保
- - '##'
  - 我需要人寿保险吗？需要多少？
- - '##'
  - 生命保险的需求导向法
- - '##'
  - 定期寿险 vs. 现金价值寿险
- - '###'
  - 定期寿险的类型
- - '###'
  - 现金价值保险的类型
- - '##'
  - 保险公司选择与评级
- - '#'
  - 5. 保障你的健康与长期护理
- - '##'
  - 选择健康保险政策时的注意事项
- - '###'
  - 考虑加入雇主提供的保险计划
- - '###'
  - 仔细审查计划细节
- - '###'
  - 灵活性需要成本
- - '###'
  - 了解你的权利
- - '##'
  - 2010 年《患者保护与平价医疗法案》
- - '##'
  - 医疗保险单类型
- - '###'
  - 补偿型（按服务收费）保单
- - '###'
  - 管理式医疗政策
- - '###'
  - 健康储蓄账户
- - '##'
  - 离职后医疗保险的延续
- - '##'
  - 医疗保险的便携性
- - '##'
  - 联邦医疗保险与补充医疗保险
- - '##'
  - 长期护理保险在保护财富中的重要性
- - '##'
  - 长期护理保险的替代方案
- - '#'
  - 6. 为您的赚钱能力投保
- - '##'
  - 您的赚钱能力损失是否已得到充分保障？
- - '##'
  - 残疾的定义
- - '##'
  - 个人残疾保单中的其他重要条款
- - '##'
  - 保单持续条款
- - '##'
  - 需考虑的其他保单福利
- - '##'
  - 保单除外责任
- - '##'
  - 购买个人伤残收入保险前应询问的问题
- - '#'
  - 7. 为您的财产投保
- - '##'
  - 为您的房屋投保时需要考虑的事项
- - '###'
  - 保险责任 A： dwelling 房屋
- - '###'
  - 保险责任 B： 其他建筑物
- - '###'
  - 保险责任 C： 室内财产或个人财产
- - '###'
  - 保险责任 D： 使用损失
- - '###'
  - 保险责任 E： 个人责任
- - '###'
  - 保险责任 F： 对他人的医疗费用支付
- - '##'
  - 房主保险类型（以及你需要的哪种）
- - '##'
  - 汽车保险时需要考虑什么
- - '###'
  - 险种 A：个人责任险
- - '###'
  - 险种 B：医疗费用险
- - '###'
  - 险种 C：未投保驾驶人险
- - '###'
  - 险种 D：物理损坏或损失险
- - '##'
  - 无过错保险
- - '##'
  - 伞式责任保险
- - '##'
  - 商业财产保险
- - '#'
  - 8. 优化您的就业福利
- - '##'
  - 团体医疗与牙科保险
- - '##'
  - 团体人寿保险
- - '##'
  - 团体残障保险
- - '##'
  - 团体长期护理保险
- - '##'
  - 受抚养人护理援助
- - '##'
  - 雇主教育援助
- - '##'
  - 通过雇主赞助计划为退休储蓄
- - '###'
  - 第 401(k)条退休计划
- - '###'
  - 第 403(b)条退休计划
- - '###'
  - 其他退休计划
- - '##'
  - 公司股票购买计划
- - '##'
  - 股票期权及其他形式的激励性薪酬
- - '##'
  - 限制性股票
- - '###'
  - 不合格递延薪酬
- - '#'
  - 第三部分
- - '#'
  - 9. 投资金融资产
- - '##'
  - 现金投资及其使用时机
- - '###'
  - 银行存款
- - '###'
  - 货币市场存款
- - '##'
  - 债券及其适用时机
- - '###'
  - 公司债券
- - '###'
  - 政府债券
- - '###'
  - 市政债券
- - '###'
  - 债券作为投资组合的一部分
- - '##'
  - 股票及其使用时机
- - '###'
  - 股票作为投资组合的一部分
- - '##'
  - 共同基金及其使用时机
- - '###'
  - 指数基金
- - '###'
  - 交易所交易基金
- - '###'
  - 共同基金：你投资组合的一部分
- - '##'
  - 国际投资
- - '#'
  - 10. 投资实物资产
- - '##'
  - 房地产直接投资
- - '###'
  - 度假住宅
- - '###'
  - 出租住宅
- - '###'
  - 商业房地产
- - '###'
  - 未开发土地
- - '##'
  - 房地产的间接投资
- - '###'
  - 房地产投资信托基金
- - '###'
  - 房地产有限合伙
- - '###'
  - 房地产投资中杠杆的运用
- - '###'
  - 相关性
- - '##'
  - 金融资产与实物资产：哪个更胜一筹？
- - '#'
  - 11. 投资于使用资产
- - '##'
  - 将住房视为投资
- - '##'
  - 购房与租房
- - '###'
  - 购房还是租房分析
- - '####'
  - 购房成本
- - '####'
  - 租房成本
- - '##'
  - 出售你的房屋
- - '##'
  - 汽车：你真的需要那辆新的兰博基尼吗？
- - '##'
  - 有形个人财产与收藏品
- - '#'
  - 第四部分：捍卫财富
- - '#'
  - 12. 所得税规划与管理
- - '##'
  - 所得税税率、预扣税和预估税基础知识
- - '##'
  - 社会保障和医疗保险税
- - '##'
  - 常规所得税与个人替代性最低税
- - '##'
  - 基本税务规划技巧#1：避税
- - '###'
  - 避税 vs. 逃税
- - '##'
  - '基本税务筹划技巧 #2：延迟纳税'
- - '##'
  - '基本税务筹划技巧 #3：收入转换'
- - '##'
  - 节税型投资
- - '##'
  - 您能从自己的纳税申报表中学到什么
- - '#'
  - 13. 转移税规划与管理
- - '##'
  - 生前赠与的优势
- - '##'
  - 赠与未成年人的礼物
- - '##'
  - 信托使用基础入门
- - '###'
  - 可撤销信托
- - '###'
  - 不可撤销信托
- - '##'
  - 总遗产的构成与估值
- - '##'
  - 遗产可获得的扣除与税收抵免
- - '##'
  - 税率与死亡税的可能废除
- - '##'
  - 我是否真的想把一切都留给配偶或慈善机构？
- - '##'
  - 隔代传承的意外风险
- - '#'
  - 14. 危及财富的生活事件
- - '##'
  - 离婚
- - '###'
  - 赡养费
- - '###'
  - 子女抚养费
- - '####'
  - 子女税收抵免
- - '###'
  - 财产分割协议
- - '###'
  - 主要住所
- - '##'
  - 失业
- - '##'
  - 配偶或生活伴侣去世
- - '###'
  - 联名持有资产
- - '###'
  - 使用受益人指定
- - '###'
  - 设立并资助可撤销生前信托
- - '##'
  - 抚养年迈父母
- - '###'
  - 为所得税目的将父母列为被抚养人
- - '##'
  - 发育障碍儿童
- - '##'
  - 个人身体或精神上的无行为能力
- - '#'
  - 第五部分
- - '#'
  - 15. 为子女的高等教育做规划
- - '##'
  - 我需要多少钱？
- - '##'
  - 以谁的名义存钱？
- - '###'
  - 经济援助类型
- - '##'
  - 如何储蓄？
- - '###'
  - 托管账户
- - '###'
  - 未成年人非劳动收入税
- - '###'
  - 教育储蓄账户
- - '###'
  - 第 529 节储蓄计划
- - '###'
  - 其他大学储蓄方式
- - '##'
  - 可用于支付大学费用的税收减免和抵免
- - '###'
  - 学生贷款利息扣除
- - '###'
  - 合格高等教育学费及杂费扣除
- - '###'
  - 高等教育税收抵免
- - '####'
  - 美国机会税收抵免
- - '####'
  - 终身学习抵税额度
- - '##'
  - 税务协调规则：为什么我不能这样做？
- - '##'
  - 使用罗斯个人退休账户资助大学教育
- - '#'
  - 16. 规划退休的财务方面
- - '##'
  - 我需要多少钱？
- - '##'
  - 退休规划中的其他问题
- - '###'
  - 房贷支出
- - '###'
  - 医疗保健费用
- - '##'
  - 退休的财务风险
- - '##'
  - 退休储蓄的“三脚凳”
- - '###'
  - 雇主赞助的退休计划
- - '###'
  - 个人储蓄计划
- - '###'
  - 社会保障
- - '##'
  - 我应该在何时选择开始领取社会保障退休福利？
- - '##'
  - 理解雇主资助退休计划的分配选项
- - '##'
  - 最低强制分配
- - '###'
  - 无漏洞可钻
- - '##'
  - 个人退休账户（IRA）的转存与转换
- - '###'
  - 个人退休账户（IRA）转换
- - '##'
  - 年金在退休规划中的运用
- - '#'
  - 17. 退休期间每年应提取多少钱？
- - '##'
  - 退休生活方式需求规划
- - '###'
  - 退休人员的住房选择
- - '####'
  - 独栋住宅
- - '####'
  - 联排别墅
- - '####'
  - 公寓
- - '####'
  - 公寓（租赁型）
- - '####'
  - 与一个或多个子女同住
- - '####'
  - 独立生活社区
- - '####'
  - 辅助生活社区
- - '####'
  - 记忆护理单元
- - '####'
  - 持续护理退休社区
- - '####'
  - 专业护理机构
- - '####'
  - 护理院护理
- - '##'
  - 利用你的住房为退休提供资金：反向抵押贷款
- - '##'
  - 退休期间我需要人寿保险吗？
- - '##'
  - 养老金最大化与退休人员健康保险
- - '###'
  - 养老金最大化
- - '###'
  - 退休人员健康保险
- - '####'
  - 方案一：COBRA 权利
- - '####'
  - 方案二：健康储蓄账户
- - '####'
  - 方案三：个人健康保险保单
- - '####'
  - 方案四：健康维护组织
- - '####'
  - 方案五：州政府担保保单
- - '##'
  - 联邦医疗保险与联邦医疗保险补充保险
- - '##'
  - 所以，我退休了！然后呢？
- - '###'
  - 未来工作
- - '###'
  - 教育
- - '###'
  - 旅行与休闲
- - '###'
  - 适应变化
- - '#'
  - 18. 规划其他终身财务目标
- - '##'
  - 创办自己的企业
- - '###'
  - 用你已有的知识开启事业
- - '###'
  - 撰写商业计划书
- - '###'
  - 考虑企业运营形式
- - '####'
  - 个人责任的可能性
- - '####'
  - 成立难易度与融资能力
- - '####'
  - 所得税影响
- - '###'
  - 招募拥有不同优势的人才
- - '###'
  - 规划企业传承
- - '##'
  - 购买个人住宅
- - '###'
  - 为购房储蓄
- - '###'
  - 了解抵押贷款类型
- - '###'
  - 购买和使用度假屋
- - '###'
  - 同类交换
- - '####'
  - 合格个人住宅信托
- - '##'
  - 投资意外之财：假如你中了彩票！
- - '#'
  - 第六部分
- - '#'
  - 19. 遗产规划
- - '##'
  - 我需要立遗嘱吗？
- - '##'
  - 通过指定受益人方式传承财产
- - '##'
  - 财产共有登记
- - '##'
  - 是否应避免死后遗产认证程序？
- - '##'
  - 遗产税
- - '###'
  - 表 19-2. 遗产统一抵免额与适用免税额等值金额
- - '###'
  - 表 19-1. 联邦统一遗产与赠与税税率等级及边际税率
- - '##'
  - 持久性授权委托书的重要性
- - '##'
  - 医疗决策代理人的选择
- - '##'
  - 为自身丧失行为能力做规划
- - '##'
  - 持久授权书的潜在问题
- - '###'
  - 示例场景
- - '##'
  - 生前遗嘱
- - '###'
  - 生前遗嘱与 DPOAHC 的区别
- - '##'
  - 个人指示函
- - '##'
  - 何时应修改我的遗产规划？
- - '#'
  - 20. 慈善捐赠
- - '##'
  - 选择受益的慈善机构
- - '###'
  - 公共慈善机构
- - '###'
  - 私人慈善机构
- - '###'
  - 凭证要求
- - '##'
  - 利用信托和年金向慈善机构捐赠
- - '###'
  - 慈善信托
- - '##'
  - 慈善礼品年金
- - '##'
  - 致敬，致敬你亲爱的母校
- - '##'
  - 私募基金会
- - '##'
  - 捐赠人建议基金
- - '#'
  - 第七部分
- - '#'
  - 21. 收获回报
- - '##'
  - 附录 A：样本数据收集表
- - '##'
  - 附录 B：样本预算
- - '##'
  - 附录 C：授权委托书
- - '###'
  - 持久性一般及财务授权委托书
- - '####'
  - 第 1 节：代理人的指定
- - '####'
  - 第 2 节：授权委托书的生效日期
- - '####'
  - 第 3 节：权力
- - '####'
  - 第 4 节：批准；影印件的使用；先前授权书的撤销：文书的解释
- - '##'
  - 附录 D：关于医疗或外科治疗声明及医疗永久授权书
- - '###'
  - 关于医疗或外科治疗声明
- - '####'
  - 维持生命程序
- - '####'
  - 人工营养
- - '####'
  - 其他具体要求：
- - '###'
  - 医疗永久授权书
- - '####'
  - 医疗保健代理人指定
- - '####'
  - 医疗永久授权书的设立
- - '####'
  - 授予权限的一般声明
- - '####'
  - 医疗记录查阅权限
- - '####'
  - 预先医疗指令
- - '####'
  - 解剖、遗体捐赠及遗骸处置
- - '####'
  - 指定备用代理人
- - '####'
  - 指定监护人与财产管理人
- - '####'
  - 一般规定
- - '#####'
  - 免责与第三方信赖
- - '#####'
  - 可分割性
- - '#####'
  - 意向声明
- - '#####'
  - 条款不一致
- - '#####'
  - 撤销先前的授权
- - '#####'
  - 适用法律
- - '####'
  - 见证人声明
- - '##'
  - 附录 E：个人指示信样本
- - '##'
  - 术语表
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '##'
  - 索引
- - '###'
  - A
- - '####'
  - 资产
- - '###'
  - B
- - '####'
  - 企业运营
- - '###'
  - C
- - '####'
  - 现金流与债务管理
- - '####'
  - 现金价值保险与定期保险
- - '####'
  - 慈善福利
- - '####'
  - 子女高等教育
- - '####'
  - 公司债券基金
- - '####'
  - 公司债券
- - '###'
  - D
- - '####'
  - 伤残收入保险保单
- - '###'
  - E
- - '####'
  - 危及财富
- - '####'
  - 规划技巧
- - '####'
  - 遗产规划
- - '###'
  - F
- - '####'
  - 金融资产投资
- - '#####'
  - 债券
- - '#####'
  - 现金投资
- - '#####'
  - 共同基金
- - '#####'
  - 股票
- - '####'
  - 财务目标
- - '#####'
  - 抵押贷款
- - '#####'
  - 个人居所
- - '####'
  - 财务规划师
- - '####'
  - 财务规划流程
- - '####'
  - 财务规划专业人士
- - '####'
  - 金融产品
- - '####'
  - 附加福利
- - '###'
  - G
- - '###'
  - H
- - '####'
  - 健康保险
- - '#####'
  - Medigap
- - '#####'
  - 保单选择
- - '#####'
  - 保单类型
- - '####'
  - 房主保险
- - '###'
  - I
- - '####'
  - 所得税规划与管理
- - '####'
  - 保险公司评级机构
- - '####'
  - 投资资产
- - '####'
  - 投资风险
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '####'
  - 生命周期规划
- - '####'
  - 人寿保险
- - '####'
  - 长期护理保险
- - '#####'
  - 类型
- - '#####'
  - 除外责任与限制
- - '###'
  - M
- - '####'
  - 抵押贷款
- - '####'
  - 共同基金
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '####'
  - 个人现金流量表
- - '###'
  - Q
- - '###'
  - R
- - '####'
  - 房地产直接投资
- - '####'
  - 金融资产相关性与金融资产
- - '####'
  - 退休规划
- - '###'
  - S
- - '####'
  - 个人财务状况表
- - '###'
  - T
- - '####'
  - 避税
- - '####'
  - 转移税规划与管理
- - '####'
  - 信托优势
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X, Y
- - '####'
  - 财富
- - '####'
  - 财富积累与管理策略
- - '###'
  - Z
