name: Quantitative Trading Strategies Using Python
name_cn: Python 量化交易策略使用指南
slug: quantitative-trading-strategies-using-python
toc:
- - '#'
  - 第1章 量化交易：导论
- - '##'
  - 量化交易概述
- - '###'
  - 模型开发工作流
- - '###'
  - 机构算法交易
- - '####'
  - 生成多个随机整数
- - '####'
  - 随机采样两个索引以识别冰山订单
- - '####'
  - 检索冰山订单
- - '###'
  - 成为量化交易员
- - '###'
  - 主要资产类别与衍生品
- - '###'
  - 可交易资产的分组
- - '###'
  - 常见交易途径与步骤
- - '###'
  - 市场结构
- - '###'
  - 主要的买方股票投资者类型
- - '###'
  - 做市
- - '###'
  - 超短线交易
- - '###'
  - 投资组合再平衡
- - '##'
  - 金融数据分析入门
- - '###'
  - 总结股票价格
- - '###'
  - 下载股票价格数据
- - '####'
  - Ticker 模块使用示例
- - '####'
  - 使用 Ticker 模块访问股票数据
- - '####'
  - 获取股票信息
- - '####'
  - access a specific attribute from the dictionary
- - '####'
  - download daily stock price data by passing in specified ticker and date range
- - '####'
  - view the first few rows.
- - '####'
  - check data dimension/size
- - '##'
  - 可视化股票价格数据
- - '####'
  - plot closing price as a time series chart
- - '####'
  - overlay the trading volume
- - '####'
  - rescale volume
- - '####'
  - 切换到烛台图
- - '##'
  - 本章小结
- - '##'
  - 练习
- - '#'
  - 第2章 电子市场
- - '##'
  - 介绍电子市场
- - '###'
  - 电子订单
- - '###'
  - 自营交易与代理交易
- - '###'
  - 订单匹配系统
- - '###'
  - 市价单
- - '###'
  - 限价单
- - '###'
  - 限价订单簿
- - '###'
  - 显示订单与非显示订单
- - '####'
  - 止损单
- - '####'
  - 止损限价单
- - '###'
  - 挂单
- - '###'
  - 追踪止损单
- - '###'
  - 触价市价单
- - '###'
  - 主要订单类型总结
- - '###'
  - 更多订单类型：限价与撤销
- - '###'
  - 价格影响
- - '###'
  - 订单流
- - '##'
  - 处理限价订单簿数据
- - '####'
  - 理解标签分布
- - '####'
  - 理解量价数据
- - '####'
  - 将买和卖连接起来，形成完整的订单簿视图
- - '####'
  - 将列重命名为 1->20
- - '####'
  - 可视化价格变动
- - '##'
  - 本章小结
- - '##'
  - 练习题
- - '#'
  - 第3章 远期与期货合约
- - '##'
  - 介绍远期合约与期货合约
- - '###'
  - 期货合约的参数
- - '###'
  - 套期保值与投机
- - '###'
  - 到期义务
- - '###'
  - 期货合约中的杠杆
- - '###'
  - 清算所
- - '###'
  - 逐日盯市
- - '###'
  - 远期合约定价
- - '###'
  - 期货合约定价
- - '####'
  - 期货升水与期货贴水
- - '####'
  - 处理期货数据
- - '####'
  - 用于数据处理
- - '####'
  - 用于获取金融数据
- - '####'
  - 用于可视化
- - '####'
  - 下载铂金价格
- - '####'
  - 将索引设置为 datetime 类型
- - '####'
  - 绘制收盘价
- - '####'
  - 设置标题及坐标轴的标签和大小
- - '####'
  - 显示图表
- - '####'
  - 获取黄金和铜的期货价格
- - '####'
  - 将索引设置为 datetime 类型
- - '####'
  - 显示最后五行
- - '####'
  - 设置图形大小
- - '####'
  - 绘制两个期货的收盘价
- - '####'
  - 设置标题及坐标轴标签和大小
- - '####'
  - 显示图表
- - '##'
  - 添加技术指标
- - '####'
  - 计算 RSI
- - '####'
  - 计算布林带
- - '####'
  - 计算 MACD
- - '####'
  - 为每个指标创建子图
- - '####'
  - 绘制收盘价
- - '####'
  - 绘制 RSI
- - '####'
  - 绘制布林带
- - '####'
  - 绘制 MACD
- - '##'
  - 本章小结
- - '##'
  - 练习题
- - '#'
  - 第4章 理解风险与回报
- - '##'
  - 风险与回报的权衡
- - '##'
  - 分析回报
- - '###'
  - 处理模拟收益率
- - '###'
  - 1+R 格式
- - '###'
  - 终端收益（Terminal Return）
- - '###'
  - 含股息的股票收益
- - '###'
  - 多期收益
- - '###'
  - 年化收益率
- - '###'
  - 从价格数据计算单期收益率
- - '###'
  - 计算两期最终收益率
- - '###'
  - 计算年化收益率
- - '##'
  - 分析风险
- - '###'
  - 介绍方差与标准差
- - '###'
  - 年化波动率
- - '###'
  - 通过夏普比率结合风险与收益
- - '###'
  - 使用股票价格数据
- - '####'
  - 将 datetime 索引转换为日期格式
- - '####'
  - 保留调整后的收盘价
- - '####'
  - 计算均值、方差和标准差
- - '##'
  - 计算年化波动率
- - '##'
  - 计算年化收益
- - '##'
  - 计算夏普比率
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 第5章 趋势跟踪策略
- - '##'
  - 处理对数收益
- - '###'
  - Q8：使用对数收益率计算期末收益率。它与 Q4 的结果相等吗？
- - '###'
  - Q9：讨论使用对数收益率的优点。
- - '####'
  - 使用对数收益率分析股票价格
- - '####'
  - 单期百分比收益率
- - '####'
  - 期末收益率
- - '####'
  - 累计收益率
- - '####'
  - 检查期末收益率是否相等
- - '####'
  - 对数收益率（1+R 格式）
- - '####'
  - 使用对数收益率计算累计收益率
- - '####'
  - 检查期末收益率是否相等
- - '##'
  - 趋势交易简介
- - '##'
  - 理解技术指标
- - '###'
  - 移动平均线介绍
- - '###'
  - 深入探讨简单移动平均线
- - '####'
  - 绘制调整后收盘价
- - '####'
  - 设置标题和坐标轴的标签及大小
- - '####'
  - 显示图表
- - '####'
  - 折线图的颜色
- - '####'
  - 绘制原始价格和 SMA 的折线图
- - '####'
  - 修改刻度大小
- - '####'
  - 标题和标签
- - '####'
  - 折线图的颜色
- - '####'
  - 绘制原始价格和 SMA 的折线图
- - '####'
  - 修改刻度大小
- - '####'
  - 标题和标签
- - '###'
  - 深入理解指数移动平均线
- - '###'
  - 实现趋势跟踪策略
- - '####'
  - Column Non-Null Count Dtype
- - '####'
  - 向未来移动一天，以便每天使用截至昨天的信息来为明天做出交易决策
- - '####'
  - 识别买入信号
- - '####'
  - 识别卖出信号
- - '####'
  - 买入并持有策略的最终收益率
- - '####'
  - 趋势跟踪策略的最终收益率
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 第6章 动量交易策略
- - '##'
  - 动量交易介绍
- - '###'
  - 深入探讨动量交易
- - '###'
  - 与趋势跟踪策略的对比
- - '###'
  - 观察回溯窗口的作用
- - '###'
  - 趋势跟踪策略详解
- - '##'
  - 实现动量交易策略
- - '###'
  - 获取道琼斯指数股票代码
- - '####'
  - Send GET request
- - '####'
  - Get the symbols table
- - '####'
  - Convert table to dataframe
- - '####'
  - Cleanup
- - '####'
  - get DJI components (ticker symbols)
- - '###'
  - 下载股票价格
- - '####'
  - use the adjusted closing prices for follow-up analysis
- - '###'
  - 计算月收益率
- - '####'
  - 创建一个包含 9 个一分钟时间戳的序列
- - '###'
  - 计算六个月期末收益率
- - '####'
  - 获取过去 6 个月的历史累积收益率，作为当前月份的期末收益率
- - '###'
  - 生成交易信号
- - '####'
  - 正向最高动量
- - '####'
  - 负向最高动量
- - '###'
  - 评估样本外表现
- - '###'
  - 与买入并持有策略的比较
- - '##'
  - 本章小结
- - '##'
  - 练习题
- - '#'
  - 第7章 回测交易策略
- - '##'
  - 回测介绍
- - '##'
  - 回测的注意事项
- - '###'
  - 理解最大回撤
- - '####'
  - 最大回撤计算
- - '##'
  - 回撤风险的弊端
- - '##'
  - 计算最大回撤
- - '####'
  - Column Non-Null Count Dtype
- - '####'
  - 计算每日回撤
- - '##'
  - 回测趋势跟踪策略
- - '####'
  - 识别买入信号
- - '####'
  - 识别卖出信号
- - '####'
  - 买入并持有的终端收益
- - '####'
  - 另一种计算方法
- - '####'
  - 趋势跟踪的终端收益
- - '####'
  - 另一种计算方法
- - '####'
  - 计算买入并持有的年化收益率
- - '####'
  - 计算趋势跟踪的年化收益率
- - '####'
  - 计算年化波动率
- - '####'
  - calculate Sharpe ratio of buy-n-hold
- - '####'
  - calculate Sharpe ratio of trend following
- - '####'
  - max drawdown of buy-n-hold
- - '####'
  - max drawdown of trend following
- - '##'
  - 小结
- - '##'
  - 练习题
- - '#'
  - 第8章 基于假设检验的统计套利
- - '##'
  - 统计套利
- - '###'
  - 配对交易
- - '###'
  - 协整
- - '###'
  - 平稳性
- - '####'
  - 从正态分布生成随机样本
- - '####'
  - 从标准正态分布生成样本
- - '####'
  - 为平稳和非平稳分布各生成 100 个随机样本
- - '####'
  - 生成一个平稳样本并添加到列表
- - '####'
  - 生成一个均值递增的非平稳样本并添加到列表
- - '####'
  - 生成一个均值和标准差都递增的非平稳样本并添加到列表
- - '####'
  - 将列表绘制为折线图，并为每条线添加标签
- - '####'
  - 设置坐标轴标签
- - '####'
  - 添加图例
- - '####'
  - 显示图表
- - '####'
  - 平稳性与协整检验
- - '####'
  - test for stationarity
- - '##'
  - 协整检验
- - '####'
  - download data from yfinance
- - '####'
  - build linear regression model
- - '####'
  - Extract prices for two stocks of interest
- - '####'
  - 'target var: Y; predictor: X'
- - '####'
  - estimate linear regression coefficients of stock1 on stock2
- - '####'
  - 访问模型权重
- - '####'
  - 替代方法
- - '####'
  - 检查两组残差是否相同
- - '####'
  - 检验残差的平稳性
- - '##'
  - 相关性与协整性
- - '####'
  - 计算相关系数
- - '####'
  - 执行协整检验
- - '####'
  - 实现配对交易策略
- - '####'
  - 从 yfinance 下载数据
- - '##'
  - 识别协整的股票对
- - '####'
  - 获取所有股票对
- - '##'
  - 测试成对协整
- - '####'
  - 对每个股票对运行恩格尔-格兰杰协整检验
- - '##'
  - 获取价差
- - '####'
  - 计算 GOOG 和 MSFT 的价差
- - '####'
  - 估计线性回归系数
- - '####'
  - 将残差作为价差
- - '###'
  - 转换为 Z 分数
- - '####'
  - 通过生成均值为 0、标准差为 1 的标准正态分布来演示 Z 分数
- - '####'
  - 输入：无界标量，此处假定范围为 [-5, 5]
- - '####'
  - 输出：介于 0 和 1 之间的概率
- - '####'
  - 设置绘图
- - '####'
  - 绘制正态分布的概率密度函数
- - '####'
  - 对 Z 分数 >=1.96 和 <= -1.96 的区域进行着色
- - '####'
  - 添加标签和标题
- - '####'
  - 添加垂直线以标示 Z 分数为 1.96 和 -1.96 的位置
- - '####'
  - 显示图形
- - '####'
  - 转换为 Z 分数
- - '####'
  - Z 分数衡量价差偏离其均值多少个标准差
- - '####'
  - 使用移动窗口推导均值和标准差
- - '####'
  - 去除初始的 NA 天数
- - '###'
  - 制定交易策略
- - '####'
  - 设置入场和离场信号的阈值
- - '####'
  - 将每日头寸初始化为零
- - '####'
  - 为每只股票生成每日入场和离场信号
- - '####'
  - 计算每只股票的收益率
- - '####'
  - 计算策略的总收益率
- - '####'
  - 绘制累积收益曲线
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 第9章 使用贝叶斯优化优化交易策略
- - '##'
  - 优化交易策略
- - '###'
  - 参数化交易策略
- - '###'
  - 关于优化的更多内容
- - '####'
  - 全局优化
- - '###'
  - 目标函数
- - '####'
  - 图 9-3
- - '####'
  - 图 9-4
- - '##'
  - 贝叶斯优化
- - '####'
  - 图 9-5
- - '###'
  - 高斯过程
- - '###'
  - 采集函数
- - '###'
  - EI 与 UCB
- - '###'
  - 完整的 BO 循环
- - '####'
  - 优化配对交易策略
- - '##'
  - 作为黑箱函数的交易策略表现
- - '##'
  - 为贝叶斯优化生成训练集
- - '####'
  - 为优化生成初始训练数据集
- - '###'
  - 实现高斯过程模型
- - '####'
  - 初始化 GP 模型
- - '####'
  - 创建一个单任务精确 GP 模型实例
- - '####'
  - 默认使用带有 Matern 核函数和常数均值函数的 GP 先验
- - '####'
  - 优化 GP 超参数
- - '####'
  - 拟合 GPyTorch 模型的超参数（核函数参数和噪声方差）
- - '###'
  - 通过最大化采集函数引导顺序搜索
- - '####'
  - 定义采集函数
- - '####'
  - 调用辅助函数生成初始训练数据并初始化模型
- - '####'
  - 优化并获取新的观测值
- - '####'
  - 获取搜索边界
- - '####'
  - 每次迭代生成的并行候选位置数
- - '####'
  - 多起点优化的起始点数量
- - '####'
  - 初始化的采样数量
- - '####'
  - 优化
- - '####'
  - 观测新值
- - '####'
  - 采样输出值
- - '####'
  - 添加输出维度
- - '####'
  - print("新函数值:", new_y)
- - '##'
  - 执行顺序搜索
- - '####'
  - 单次试验
- - '####'
  - 在初始随机批次之后运行 N_ROUND 轮贝叶斯优化
- - '####'
  - 拟合模型
- - '####'
  - 对于 best_f，我们使用观测到的确切最大值
- - '####'
  - 优化并获取新的观测值
- - '####'
  - 更新训练点集
- - '####'
  - 更新进度
- - '####'
  - 重新初始化模型，以便它们为下一轮的拟合做好准备
- - '####'
  - multiple trials
- - '####'
  - number of runs to assess std of different BO loops
- - '####'
  - indicator to print diagnostics
- - '####'
  - number of steps in the outer BO loop
- - '####'
  - average over multiple trials
- - '##'
  - 本章小结
- - '##'
  - 练习题
- - '#'
  - 第10章 利用机器学习的配对交易
- - '##'
  - 配对交易中的机器学习
- - '###'
  - 机器学习工作流
- - '###'
  - 支持向量机
- - '###'
  - 随机森林
- - '####'
  - 神经网络
- - '####'
  - 使用机器学习实现配对交易策略
- - '####'
  - 从 yfinance 下载数据
- - '####'
  - 计算两项资产之间的价差
- - '##'
  - 特征工程
- - '####'
  - 定义额外的特征
- - '####'
  - 将特征组合到单个 DataFrame 中
- - '####'
  - 将数据分割为训练集和测试集
- - '###'
  - 使用 `SVM` 进行配对交易
- - '###'
  - 使用随机森林进行配对交易
- - '####'
  - 随机森林
- - '####'
  - 创建随机森林回归器
- - '####'
  - 在训练集和测试集上训练模型
- - '###'
  - 使用神经网络进行配对交易
- - '####'
  - 将数据转换为 PyTorch 张量
- - '####'
  - 定义神经网络模型
- - '####'
  - 创建神经网络模型的一个实例
- - '####'
  - 打印自定义神经网络的摘要
- - '####'
  - 定义损失函数和优化器
- - '####'
  - 训练模型
- - '####'
  - 每 10 个 epoch 打印一次损失
- - '####'
  - 在训练集和测试集上评估模型
- - '##'
  - 总结
- - '##'
  - 练习题
- - '#'
  - 附录A 术语表
- - '##'
  - 采集函数
- - '##'
  - 主动管理型投资池
- - '##'
  - 活跃交易者
- - '##'
  - '`add_constant()` 函数'
- - '##'
  - 高级订单类型
- - '##'
  - 代理订单
- - '##'
  - 代理交易
- - '##'
  - '`agg()` 函数'
- - '##'
  - 全部成交或取消 (`AON`)
- - '##'
  - '`alpha` 参数'
- - '##'
  - 年化方差
- - '##'
  - 年化收益
- - '##'
  - 年化波动率
- - '##'
  - 年金
- - '##'
  - '`apply()` 函数'
- - '##'
  - 套利
- - '##'
  - 算术平均数
- - '##'
  - 资产类别
- - '##'
  - 资产价格曲线
- - '##'
  - '`asset_return1`'
- - '##'
  - '`asset_return2`'
- - '##'
  - 增强迪基-福勒 (`ADF`) 检验
- - '##'
  - 自动化优化技术
- - '##'
  - 自动化交易
- - '##'
  - B
- - '##'
  - 回测
- - '##'
  - '`backward()` 方法'
- - '##'
  - 期货贴水
- - '##'
  - 贝叶斯优化
- - '##'
  - 大型交易所
- - '##'
  - 黑箱函数
- - '##'
  - 布林带
- - '##'
  - 债券
- - '##'
  - '`botorch.optim` 模块'
- - '##'
  - 买入并持有策略
- - '##'
  - 买方机构投资者
- - '##'
  - 买方价格
- - '##'
  - 买方散户投资者
- - '##'
  - C
- - '##'
  - 集合竞价市场
- - '##'
  - '`Candlestick()` 函数'
- - '##'
  - K 线图
- - '##'
  - 现金结算
- - '##'
  - 中央存管机构 (`CDP`)
- - '##'
  - 集中竞价市场
- - '##'
  - ChatGPT 模型
- - '##'
  - 芝加哥期货交易所 (`CBOT`)
- - '##'
  - 清算
- - '##'
  - 清算所
- - '##'
  - '`coint()` 函数'
- - '##'
  - 协整
- - '##'
  - 复利回报
- - '##'
  - 复利计算
- - '##'
  - 期货升水
- - '##'
  - 连续市场
- - '##'
  - 便利收益
- - '##'
  - '`cummax()` 函数'
- - '##'
  - '`.cumprod()` 函数'
- - '##'
  - '`cumprod()` 函数'
- - '##'
  - D
- - '##'
  - 每日回撤
- - '##'
  - 暗池
- - '##'
  - '`DataFrames`'
- - '##'
  - 数据生成过程
- - '##'
  - '`datetime` 格式'
- - '##'
  - 日内交易者
- - '##'
  - 交割
- - '##'
  - 衍生品市场
- - '##'
  - '`df2` 变量'
- - '##'
  - '`dfBidPrices`'
- - '##'
  - '`dfPrices`'
- - '##'
  - '`diff()` 函数'
- - '##'
  - 显示订单
- - '##'
  - '`DJI 股票代码`'
- - '##'
  - 道琼斯工业平均指数 (`DJIA`)
- - '##'
  - 动量交易
- - '##'
  - '`download()` 函数'
- - '##'
  - '`drawdown()`'
- - '##'
  - '`dropna()` 函数'
- - '##'
  - E
- - '##'
  - 每股收益 (`EPS`)
- - '##'
  - 电子通信网络 (`ECNs`)
- - '##'
  - 电子市场
- - '##'
  - '`E-Mini` 期货合约'
- - '##'
  - '`equals()` 函数'
- - '##'
  - 评估期表现
- - '##'
  - '`ewm()` 方法'
- - '##'
  - '`ExactMarginalLogLikelihood()` 函数'
- - '##'
  - 交易所交易基金 (`ETFs`)
- - '##'
  - 执行风险
- - '##'
  - 预期改进 (`EI`)
- - '##'
  - 探索性数据分析
- - '##'
  - 指数加权移动平均线 (`EWMA`)
- - '##'
  - 指数移动平均线 (`EMA`)
- - '##'
  - 乘方
- - '##'
  - F
- - '##'
  - '`FAK` 订单'
- - '##'
  - 特征工程
- - '##'
  - 成交并取消 (`FAK`)
- - '##'
  - 全部成交否则取消 (`FOK`)
- - '##'
  - 金融资产
- - '##'
  - 金融数据分析
- - '##'
  - 金融衍生品
- - '##'
  - 金融工具
- - '##'
  - 金融市场稳定
- - '##'
  - 金融交易
- - '##'
  - 一阶梯度方法
- - '##'
  - 第一期收益
- - '##'
  - 灵活控制
- - '##'
  - '`FOK` 订单'
- - '##'
  - 远期和期货合约
- - '##'
  - 远期合约
- - '##'
  - 期货合约
- - '##'
  - 期货数据
- - '##'
  - 期货交易
- - '##'
  - G
- - '##'
  - 高斯分布
- - '##'
  - 高斯过程 (`GP`) 模型
- - '##'
  - '`generate_initial_data()`'
- - '##'
  - '`get_stock_data()` 函数'
- - '##'
  - '`go.Bar()` 函数'
- - '##'
  - 交易资产分组
- - '##'
  - H
- - '##'
  - '`head()` 函数'
- - '##'
  - 对冲基金
- - '##'
  - 套期保值者
- - '##'
  - 对冲
- - '##'
  - 隐藏 / 非显示订单
- - '##'
  - 高频交易 (`HFT`)
- - '##'
  - 超参数调优
- - '##'
  - 假设检验
- - '##'
  - I, J, K
- - '##'
  - 冰山订单
- - '##'
  - '`idxmin()` 函数'
- - '##'
  - '`iloc()` 函数'
- - '##'
  - '`iloc()` 方法'
- - '##'
  - 立即成交否则取消 (`IOC`)
- - '##'
  - 实施趋势跟踪策略
- - '##'
  - '`info()` 函数'
- - '##'
  - '`initialize_model()`'
- - '##'
  - 输入数据组
- - '##'
  - 机构算法交易
- - '##'
  - 插值法
- - '##'
  - L
- - '##'
  - 标签分布
- - '##'
  - 杠杆
- - '##'
  - 限价订单
- - '##'
  - 限价订单簿 (`LOB`)
- - '##'
  - '`LOB` 数据'
- - '##'
  - '`loc()` 函数'
- - '##'
  - 对数收益率
- - '##'
  - 回溯窗口
- - '##'
  - M
- - '##'
  - 机器学习组件
- - '##'
  - '`make_subplots()` 函数'
- - '##'
  - 逐日盯市 (`MTM`)
- - '##'
  - 触及市价单 (`MIT`)
- - '##'
  - 做市商
- - '##'
  - 市场中性交易策略
- - '##'
  - 非持有市场订单
- - '##'
  - 市价订单
- - '##'
  - 市场参与者
- - '##'
  - 市场择时
- - '##'
  - 逐日盯市
- - '##'
  - 最大回撤
- - '##'
  - 最大对数似然 (`MLL`) 方法
- - '##'
  - '`mean()` 方法'
- - '##'
  - 均方误差
- - '##'
  - 模型开发流程
- - '##'
  - 模型训练过程
- - '##'
  - 动量交易
- - '##'
  - 指数平滑异同移动平均线 (`MACD`)
- - '##'
  - 移动平均线 (`MA`)
- - '##'
  - 多期收益
- - '##'
  - 共同基金
- - '##'
  - N
- - '##'
  - '`NaN` 值'
- - '##'
  - 纳斯达克
- - '##'
  - 北欧股票市场
- - '##'
  - 神经网络
- - '##'
  - 纽约证券交易所 (`NYSE`)
- - '##'
  - 无套利论证
- - '##'
  - 非凸函数
- - '##'
  - 非显示订单
- - '##'
  - 正常期货升水
- - '##'
  - 正态性
- - '##'
  - '`n` 期投资期限'
- - '##'
  - '`np.exp()` 函数'
- - '##'
  - '`np.mean()` 函数'
- - '##'
  - 零假设
- - '##'
  - O
- - '##'
  - 目标函数
- - '##'
  - '*OHLC* 价格'
- - '##'
  - '`OHLC` 图表'
- - '##'
  - 能量潮 (`OBV`)
- - '##'
  - 一维目标函数
- - '##'
  - 在线交易平台
- - '##'
  - 优化
- - '##'
  - 指令驱动市场
- - '##'
  - 订单流
- - '##'
  - 订单匹配系统
- - '##'
  - 订单优先规则
- - '##'
  - 订单类型
- - '##'
  - 普通最小二乘法 (`OLS`)
- - '##'
  - 场外交易 (`OTC`)
- - '##'
  - P
- - '##'
  - 配对交易
- - '##'
  - '`Pandas DataFrame`'
- - '##'
  - '`pct_change()` 函数'
- - '##'
  - '`pd.DataFrame()` 函数'
- - '##'
  - 挂钩订单
- - '##'
  - 百分比变化
- - '##'
  - 百分比收益率
- - '##'
  - '`p`-值操纵'
- - '##'
  - 实物交割
- - '##'
  - '`plot()` 函数'
- - '##'
  - '`plotly` 包'
- - '##'
  - 潜在交易机会
- - '##'
  - '`predict()` 方法'
- - '##'
  - 价格影响
- - '##'
  - 价格阶梯
- - '##'
  - 价格变动可视化
- - '##'
  - 价格优先
- - '##'
  - 价格收益
- - '##'
  - 价格滑点
- - '##'
  - 复利原理
- - '##'
  - '`prod()` 函数'
- - '##'
  - 程序化交易
- - '##'
  - 自营订单
- - '##'
  - 自营交易
- - '##'
  - Q
- - '##'
  - '`qcut()` 函数'
- - '##'
  - 量化交易
- - '##'
  - 量化交易者
- - '##'
  - 报价驱动 / 价格驱动市场
- - '##'
  - R
- - '##'
  - 随机森林
- - '##'
  - 随机森林回归器
- - '##'
  - 房地产投资信托基金 (`REITs`)
- - '##'
  - 再平衡投资组合
- - '##'
  - 再平衡
- - '##'
  - 修正线性单元 (`ReLU`)
- - '##'
  - 相对强弱指数 (`RSI`)
- - '##'
  - 最终收益
- - '##'
  - '`resample()` 函数'
- - '##'
  - '`return_df` 变量'
- - '##'
  - 收益分析
- - '##'
  - 收益值 `1+R` 格式
- - '##'
  - 风险调整后收益
- - '##'
  - 风险分析
- - '##'
  - 风险与收益权衡
- - '##'
  - 无风险债券利率
- - '##'
  - 无风险利率
- - '##'
  - '`1+R` 方法'
- - '##'
  - '`rolling()` 函数'
- - '##'
  - 均方根误差 (`RMSE`)
- - '##'
  - '`1+R` 收益率'
- - '##'
  - 基于规则的方法
- - '##'
  - S
- - '##'
  - 抢帽子交易
- - '##'
  - '`shape()` 函数'
- - '##'
  - 夏普比率
- - '##'
  - '`shift()` 函数'
- - '##'
  - 短期波动
- - '##'
  - 简单移动平均线 (`SMA`)
- - '##'
  - 新加坡投资
- - '##'
  - 新加坡交易所 (`SGX`)
- - '##'
  - 单期对数收益率
- - '##'
  - 单期对数收益
- - '##'
  - 单期百分比收益率
- - '##'
  - 单期收益
- - '##'
  - 单期波动率
- - '##'
  - 数量优先
- - '##'
  - 滑点
- - '##'
  - '`SMA-3`'
- - '##'
  - 投机者
- - '##'
  - '`S&P 500` `E-Mini` 期货合约'
- - '##'
  - 现货市场
- - '##'
  - 堆积柱状图
- - '##'
  - 标准差
- - '##'
  - 标准化
- - '##'
  - 平稳性
- - '##'
  - 统计套利
- - '##'
  - 统计概念
- - '##'
  - 统计度量
- - '##'
  - '`std()` 函数'
- - '##'
  - 股票数据
- - '##'
  - 股票价格数据
- - '##'
  - 含股息股票收益
- - '##'
  - 股票
- - '##'
  - 止损买入订单
- - '##'
  - 止损限价订单
- - '##'
  - 止损订单
- - '##'
  - 止损订单
- - '##'
  - '`summary()` 函数'
- - '##'
  - 误差平方和 (`SSE`)
- - '##'
  - 支持向量机 (`SVM`)
- - '##'
  - 对称性
- - '##'
  - T
- - '##'
  - '`tail()` 函数'
- - '##'
  - 有形和无形因素
- - '##'
  - 技术指标
- - '##'
  - 期末月收益率
- - '##'
  - 最终收益
- - '##'
  - '`Ticker()` 模块'
- - '##'
  - 时间优先
- - '##'
  - 时间序列数据
- - '##'
  - '`today()` 函数'
- - '##'
  - '`torch.Tensor()` 函数'
- - '##'
  - 可交易资产, 量化交易
- - '##'
  - 交易形成期
- - '##'
  - 交易者
- - '##'
  - 交易代理
- - '##'
  - 交易算法
- - '##'
  - 交易途径
- - '##'
  - 交易信号
- - '##'
  - 交易步骤
- - '##'
  - 交易量
- - '##'
  - 追踪止损订单
- - '##'
  - 交易
- - '##'
  - 趋势跟踪策略
- - '##'
  - 趋势交易者
- - '##'
  - 趋势交易
- - '##'
  - 两期收益
- - '##'
  - 典型模型训练过程
- - '##'
  - U
- - '##'
  - 单位根检验
- - '##'
  - 置信上界 (`UCB`)
- - '##'
  - V, W, X
- - '##'
  - '`value_counts()` 函数'
- - '##'
  - 方差和标准差
- - '##'
  - 波动率
- - '##'
  - 成交量加权平均价 (`VWAP`)
- - '##'
  - Y
- - '##'
  - Yahoo! 财经
- - '##'
  - '`yfinance` 库'
- - '##'
  - '`yfinance` 包'
- - '##'
  - Z
- - '##'
  - '`zero_grad()` 函数'
- - '##'
  - 零和博弈
- - '##'
  - '`Z`-分数'
